---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hdfs-operator-hdfs-datanode-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
