---
apiVersion: v2
name: hdfs-operator
version: "23.4.1"
appVersion: "23.4.1"
description: The Stackable Operator for Apache HDFS
home: https://github.com/stackabletech/hdfs-operator
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
